config/routes.rb
Rails.application.routes.draw do
  get 'comments/show'
  devise_for :users
  
  resources :articles do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "users#index"
   get 'profile/:id', to: 'users#show', as: 'profile'
   resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true,length: { in: 3..1000 }
    validates :description, presence: true,length: {minimum: 10}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :article
  validates :content, presence: true,length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable

  validates :first_name, presence: true  
  validates :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true ,length: {maximum: 105},uniqueness: { case_sensitive: false },format: {with: VALID_EMAIL_REGEX }       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
  
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,:last_name])
    end
  
        
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!,except: [:show, :index]
  before_action :set_article , only: [:show, :edit, :update, :destroy]
  before_action :require_same_user,only:[:edit, :update, :destroy]

  def show
    @comments = @article.comments.order(created_at: :desc)
    @comment=Comment.new
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
  end

  def new
    @article=Article.new
  end

  def edit
  end

  def create
    @article=current_user.articles.build(article_params)
     if @article.save
     flash[:notice] = "Article was created successfully"
     redirect_to @article
    else
     render :new, status: :unprocessable_entity
    end
  end

  def update
      if @article.update(article_params)
      flash[:notice] = "Article was edited successfully"
      redirect_to @article
      else
      render :edit, status: :unprocessable_entity
      end
  end
 
 def destroy
     @article.destroy
     flash[:notice] = "Article was deleted successfully"
     redirect_to articles_path
 end

  private

  def set_article
      @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
  def require_same_user
    if current_user != @article.user && !current_user.admin?
        flash[:alert]="Only author can edit or delete this article"
        redirect_to @article
  end
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!,only: [:destroy]
  before_action :set_article
  before_action :require_same_user,only:[:destroy]

  def edit
    @comment = @article.comments.find(params[:id])
    render 'articles/show'
  end

  def create
    @comment = @article.comments.build(comment_params) 
    @comment.user = current_user if user_signed_in?

    if @comment.save
      redirect_to @article, notice: 'Comment was successfully created.'
    else
      redirect_to @article, alert: 'Error creating comment.'
    end
  end

  def update
    @comment = @article.comments.find(params[:id])

    @comment.update(comment_params)
    debugger
      redirect_to @article, notice: 'Comment was successfully updated.'
    
  end

  def destroy 
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to @article, notice: 'Comment was successfully deleted.'
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin? && current_user != @comment.user
        flash[:alert]="You cannot delete this comment"
        redirect_to @article
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!,only: [:destroy]
    before_action :set_user,only: [:show,:destroy]
    before_action :require_same_user,only:[:destroy]

    def show   
        @articles =@user.articles.paginate(page: params[:page], per_page: 5)
    end

  def index
    @users=User.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    if @user.destroy
        flash[:notice] = "User and associated data were successfully deleted."
    else
        flash[:alert] = "There was a problem deleting the user."
    end
    redirect_to root_path
    end

private

def set_user
    @user =User.find(params[:id])
  end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert]="Only author can edit or delete this article"
            redirect_to @article
        end
    end    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<div class="container mt-3">
    <div class="container">
        <div class="alert alert-danger mt-3 <%= 'd-none' if !@articles.empty? %>">
            Nothing posted
        </div>
    </div>


    <% @articles.each do |article| %>
        <div class="row gx-5">
            <div class="col-md-6 mb-4">   
                <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5" data-mdb-ripple-color="light">
                    <img src="https://mdbcdn.b-cdn.net/img/new/slides/080.webp" class="img-fluid" />
                    <a href="#!">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                    </a>
                </div>
            </div>

            <div class="col-md-6 mb-4">
                <span class="badge bg-danger px-2 py-1 shadow-1-strong mb-3"><%=link_to "#{article.user.first_name} #{article.user.last_name}" ,profile_path(article.user),class: "text-decoration-none text-black"  %></span>
                <h4><strong><%= link_to article.title, article_path(article),class: "text-decoration-none text-black"%></strong></h4>
                <p class="text-muted">
                <%= truncate(article.description, length: 250) %>
                </p>
                <button  type="button" data-mdb-button-init data-mdb-ripple-init class="custom-button text-decoration-none"><%= link_to 'Read more', article_path(article),class: "text-decoration-none text-white" %></button>
                <%if user_signed_in? && (current_user == article.user || current_user.admin)%>
                    <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-primary"><%= link_to 'Edit', edit_article_path(article),class: "text-decoration-none text-black" %></button>
                                                <%= link_to "Delete", article_path(article), data: {
                                                    turbo_method: :delete,
                                                    turbo_confirm: "Are you sure?"
                                                },class: "btn btn-outline-danger" %>
                <%end %>
                <hr class="my-3" style="height: 1px;" />
                <small>Created <%= time_ago_in_words(article.created_at)%> ago,
                                        edited <%= time_ago_in_words(article.updated_at)%> ago</small>            
            </div>

        </div>
    <% end %>     
</div>   

app/views/articles/_form.html.erb
<div class="container ">
    <div class="col-10 mx-auto ">
        <div class="row justify-content-center ">
            <%= render 'layouts/validation_messages', obj: @article%>
            <%= form_with model: @article,class:"custom-bg shadow mb-3 rounded" do |f| %>
                <div class=" form-group pt-4 row ">
                    <%= f.label :title ,class: "col-sm-2 col-form-label  fs-5" %>
                    <div class="col-sm-10">
                    <%= f.text_field :title, class: "form-control shadow rounded ",placeholder: "Title of the article" %>
                    </div>
                </div>
                <div class=" form-group pt-3  row ">
                    <%= f.label :description, class:"col-sm-2 col-form-label fs-5" %>
                    <div class="col-sm-10">
                    <%= f.text_area :description, class: "form-control shadow mb-3  rounded ",  rows:"10",placeholder: "Description" %>
                    </div>
                </div>


                <div class=" col text-center">
                        <%= f.submit class: "custom-button mb-3" %>
                </div>
            </div>        
        <% end %>
        <div class="col text-center mb-4">
           <%= link_to "Cancel and return to articles",articles_path, class: "text-secondary " %>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center m-4">Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all Articles</h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article'%>
<div class="flickr_pagination mb-3">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center m-4">Create a New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row mx-5">
    <div class="col-11 justify-content-center mx-5">
        <div class="container bg-white m-4  ">
            <div class="card " >
                <div class="card-header fst-italic text-center">
                    <%if @article.user%>
                        by <%=link_to @article.user.first_name ,profile_path(@article.user),class:"text-black"  %>
                    <% end %>              
                </div>
                <div class="card-body">    
                    <h1 class="text-center"><%= @article.title %> </h1>      
                    <p class="card-text"><%= simple_format(@article.description) %></p>
                    <%if current_user && (current_user == @article.user || current_user.admin?)%>
                        <%= link_to 'Edit', edit_article_path(@article),class: "btn btn-outline-success" %>
                        <%= link_to "Delete", article_path(@article), data: {
                                                        turbo_method: :delete,
                                                        turbo_confirm: "Are you sure?"
                                                    },class: "btn btn-outline-danger"%>
                    <%end%>
                </div>
            </div>


            <div id="comments">
                <div class="container my-3 ">
                    <div class="row d-flex ">
                        <div class="col-md-9 col-lg-7">
                            <div class="card text-body">
                                <div class="card-body p-4">
                                    <h4 class="mb-2">Recent comments</h4>
                                    <hr class="my-0" style="height: 1px;" />
                                    <%= "Be the first one to comment" if @article.comments.empty? %>
                                    <%= render @article.comments %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="my-3">
                        <%= render 'comments/form'%>
                    </div>
                </div>



                <div class="col text-center m-4">
                        <%= link_to "Return",articles_path, class: "text-secondary " %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/comments/_comment.html.erb
<div class="d-flex flex-start mt-3">
    <img class="rounded-circle shadow-1-strong me-3"
    src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(23).webp" alt="avatar" width="60" height="60" />
    <div>
        <h6 class="fw-bold mb-1">
        <% if comment.user %>
            <%= link_to "#{comment.user.first_name} #{comment.user.last_name}", profile_path(comment.user), class: "text-decoration-none" %>
        <% else %>
            Anonymous
        <% end %>
        </h6>
        <div class="d-flex align-items-center mb-3">
            <p class="mb-0">Posted <%= time_ago_in_words(comment.created_at)%> ago</p>
            <% if current_user && (comment.user == current_user || current_user.admin || current_user==comment.article.user)%>
                <%= link_to article_comment_path(article_id: comment.article_id, id: comment.id), 
                                                    method: :delete,
                                                    data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                                                    class: "btn btn-sm btn-danger ms-2" do %>
                                                            <%= fa_icon 'trash' %>     
                                                    <% end %>
                <%= link_to edit_article_comment_path(@article, comment), class: "btn btn-sm btn-primary ms-2" do %>
                    <%= fa_icon 'edit' %>
                <% end %>
            <% end %>
            <a href="#!" class="link-muted"><i class="fas fa-heart ms-2"></i></a>
        </div>
        <p class="mb-0"><%= comment.content.html_safe %></p>
    </div>
</div>
<hr class="my-0" style="height: 1px;" />         

app/views/comments/_form.html.erb
<%= form_with(model: [@article, @comment], local: true) do |form| %>
    <p><%= form.text_area :content, class: 'tinymce',placeholder: "Type here" %></p>
    <%= form.submit %>
<% end %>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class="alert alert-success alert-dismissible fade show" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>       
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>       
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid mx-5 ">
    <%= link_to "Arti", articles_path, class: "navbar-brand logo" %>
    
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
         <li class="nav-item">
            <%= link_to "Feed", articles_path, class: "nav-link active" %>
        </li>
         <li class="nav-item">
            <%= link_to "Users", root_path, class: "nav-link active" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Create Article", new_article_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
            <%= link_to "My Articles", profile_path(current_user), class: "nav-link active" %>
        </li>
                </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item pt-2">
              <%= link_to edit_user_registration_path(current_user) do %>
              <%= fa_icon 'pencil' %>
              <% end %>
               </li>
            <li class="nav-item p-2">
            <%= fa_icon 'user' %> <%= "#{current_user.first_name} #{current_user.last_name}" %>
          </li>
          <li class="nav-item">
            <%= button_to "LogOut", destroy_user_session_path, method: :delete,class: "btn btn-xs btn-danger mx-3" %>
          </li>
          <% else %>
        </ul>
      </div>
    
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= button_to "SignUp", new_user_registration_path, method: :get, class: "custom-button" %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/_validation_messages.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">  
        <h2 class="alert-heading" >The following errors prevented <%= obj.class.name.downcase%> from being saved </h2>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
            <% end %>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>       
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assi4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tiny.cloud/1/ks2n1rxtsnxp8107jeargcxlwcuq033q08o8nrvbbdrn5a3g/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  </head>

  <body>
  <%= render "layouts/nav" %>
      <div id="page-content" >
      <%= render 'layouts/messages' %>
      <%= yield %> 
    </div>
 
</html>

app/views/users/index.html.erb
<h1 class="text-center my-4">Users</h1>
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>
<div class="container">
    
        <div class="row ">
            <% @users.each do |user| %>
            <div class="col-4 mt-4  ">
                <div class="card  shadow mb-5 bg-body rounded">
                    
                    <div class="card-body ">
                        <%= link_to profile_path(user), class: "text-black text-decoration-none fs-2" do %>
                            <%= fa_icon 'user' %> <%= "#{user.first_name} #{user.last_name}" %>
                        <% end %>
                        <h5 class="card-title mt-3"><%= pluralize(user.articles.count,"article")%></h5>
                        <p class="card-text"><%= user.email%></p>
                    </div>
                    <div class="card-footer text-muted  ">
                        <small>Joined <%= time_ago_in_words(user.created_at)%> ago,
                        </small>
                    </div>
                </div>
            </div>
        
    <% end %>    
    </div> 
</div>   
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/show.html.erb
<div class="row d-flex justify-content-center m-4">
    <div class="col col-md-9 col-lg-7 col-xl-6">
      <div class="card mt-5" style="border-radius: 15px;">
        <div class="card-body p-4">
          <div class="d-flex">
            <div class="flex-shrink-0">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp"
                alt="Generic placeholder image" class="img-fluid" style="width: 180px; border-radius: 10px;">
            </div>
            <div class="flex-grow-1 ms-3">
              <h5 class="mb-1"><%= "#{@user.first_name} #{@user.last_name}"%></h5>
              <p class="mb-2 pb-1"><%= @user.email%></p>
              <div class="d-flex justify-content-start rounded-3 p-2 mb-2 bg-body-tertiary">
                <div>
                  <p class="small text-muted mb-1">Articles</p>
                  <p class="mb-0"><%=@user.articles.count%></p>
                </div>
                <div class="px-3">
                  <p class="small text-muted mb-1">Followers</p>
                  <p class="mb-0">976</p>
                </div>
                <div>
                  <p class="small text-muted mb-1">Rating</p>
                  <p class="mb-0">8.5</p>
                </div>
            </div>
            <div class="d-flex pt-1">
                <%if current_user && (current_user ==@user || current_user.admin?)%>
                    <div class="text-center m-4">
                    <%= link_to 'Edit  Profile ', edit_user_registration_path(@user),class: "custom-button text-decoration-none" if current_user ==@user %>               
                    </div>
                    <div class="text-center my-3">
                        <%= button_to "Delete Profile", current_user.admin? ? user_path : user_registration_path, method: :delete, class: "btn btn-xs btn-danger" %>           
                    </div>

                <%end%>
            </div >
              <small >Joined <%= time_ago_in_words(@user.created_at)%> ago,</small>
        </div>
    </div>
    </div>
      </div>
    </div>
  </div>
<h3 class="text-center m-4">Articles</h3>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles/article'%>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>